name: Java CI with Gradle for NCR test.   # 1. 이름 변경 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Build Docker file
      run: docker build -t nhncloud_ncrtest-$GITHUB_SHA .
      shell: bash

    - name: Tagging NCR         #Docker image 정보를 변경 (NHN Cloud에 접근하기 위함)
      run: docker tag nhncloud_ncrtest-$GITHUB_SHA:latest 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/nhncloud_ncrtest-$GITHUB_SHA:latest
      shell: bash

    - name: Login to NHN Cloud    #NHN Cloud접근을 위한 Authentication 추가.
      uses: docker/login-action@v2
      with:
        registry: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
        username: CQBbNIZmQNrLx5iKXJZq
        password: c65CEx6EmuSyk4x4

    - name: Upload to NCR         #NHN Cloud에 로그인 완료 하고 생성된 docker image를 업로드 
      run: docker push 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/nhncloud_ncrtest-$GITHUB_SHA:latest
      shell: bash

