# logging-deploy.yml
name: credential Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env: # 새로 추가한 부분
  PROJECT_NAME: nhncloud_ncrtest
  NHN_REGISTRY: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
  NHN_USER_ACCESS_KEY: CQBbNIZmQNrLx5iKXJZq
  NHN_SECRET_KEY: c65CEx6EmuSyk4x4

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to NHN Cloud
        uses: docker/login-action@v2
        with:
          registry: $NHN_REGISTRY
          username: $NHN_USER_ACCESS_KEY
          password: $NHN_SECRET_KEY
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17 # JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$PROJECT_NAME-$GITHUB_SHA.zip .
        shell: bash

      - name: Check build fild
        run: ls -al ././$PROJECT_NAME-$GITHUB_SHA.zip
        
      - name: Check all
        run: ls -al
