# logging-deploy.yml
name: credential Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env: # 새로 추가한 부분
  PROJECT_NAME: nhncloud_ncrtest
  NHN_REGISTRY: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
  NHN_USER_ACCESS_KEY: CQBbNIZmQNrLx5iKXJZq
  NHN_SECRET_KEY: c65CEx6EmuSyk4x4

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to NHN Cloud
        uses: docker/login-action@v2
        with:
          registry: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
          username: CQBbNIZmQNrLx5iKXJZq
          password: c65CEx6EmuSyk4x4
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17 # JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Copy jar file 
        run: mv ./build/libs/ncrtest-0.0.1-SNAPSHOT.jar ./
        shell: bash
        
      - name: Build Docker file
        run: docker build -t ncrtest-$GITHUB_SHA .
        shell: bash
        
      - name: Tagging NCR
        run: docker tag ncrtest-$GITHUB_SHA:latest 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/$GITHUB_SHA:latest
        shell: bash
        
      - name: Upload to NCR
        run: docker push 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/$GITHUB_SHA:latest
        shell: bash
