name: Java CI with Gradle for NCR test.   # 1. 이름 변경 

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env: # 새로 추가한 부분
  PROJECT_NAME: nhncloud_ncrtest
  NHN_REGISTRY: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
  NHN_USER_ACCESS_KEY: CQBbNIZmQNrLx5iKXJZq
  NHN_SECRET_KEY: c65CEx6EmuSyk4x4

jobs:     
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Build Docker file
      run: docker build -t $PROJECT_NAME-$GITHUB_SHA .
      shell: bash

    - name: Tagging NCR
      run: docker tag $PROJECT_NAME-$GITHUB_SHA:latest 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/$PROJECT_NAME-$GITHUB_SHA:latest
      shell: bash

    - name: Login to NHN Cloud
      uses: docker/login-action@v2
      with:
        registry: 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test
        username: CQBbNIZmQNrLx5iKXJZq
        password: c65CEx6EmuSyk4x4

    - name: Upload to NCR
      run: docker push 127ff7ca-kr1-registry.container.nhncloud.com/ncr_gitaction_test/$PROJECT_NAME-$GITHUB_SHA:latest
      shell: bash



